# Generated by Django 5.0.2 on 2024-02-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ide", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testcase",
            name="problem",
        ),
        migrations.AddField(
            model_name="problem",
            name="test_cases",
            field=models.ManyToManyField(to="ide.testcase"),
        ),
    ]
