# Generated by Django 5.0.2 on 2024-02-19 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ide", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="languages_supported",
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name="TestCaseResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("output", models.TextField()),
                (
                    "verdict",
                    models.CharField(
                        choices=[("pass", "Pass"), ("fail", "Fail")], max_length=20
                    ),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="ide.problemattempt",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ide.testcase"
                    ),
                ),
            ],
        ),
    ]
