# Generated by Django 5.0.2 on 2024-02-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ide", "0002_problem_expected_output_problem_hidden_problem_input_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input", models.TextField()),
                ("expected_output", models.TextField()),
                ("hidden", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name="problem",
            name="expected_output",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="hidden",
        ),
        migrations.RemoveField(
            model_name="problem",
            name="input",
        ),
    ]
