# Generated by Django 5.0.2 on 2024-02-18 10:27

import django.db.models.deletion
import ide.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ide", "0003_testcase_remove_problem_expected_output_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcase",
            name="problem",
            field=models.ForeignKey(
                default=ide.models.get_default_problem,
                on_delete=django.db.models.deletion.CASCADE,
                to="ide.problem",
            ),
        ),
    ]
